name=input("Enter a name:")
age=int(input("Enter a age:"))
sex=input("Enter the sex of employee:")
caste=input("Enter a caste:")
contact=input("Enter a contact number:")
add=input("Enter a address:")
exp=int(input("Enter a experience in years:"))
qual=input("Enter a Qualification:")
print("**************************************")
print("------Employee details--------")
print("**************************************")
print("1. NAME:",name)
print("2.AGE:",age)
print("3.CASTE:",caste)
print("4.SEX:",sex)
print("5.CONTACT NUMBER:",contact)
print("6.ADDRESS:",add)
print("7.EXPERIENCE:",exp)
print("8.QUALIFICATION:",qual)