print("------------------------------------------------------------------")
print("---------------------- Create Related Tables ---------------------")
print("------------------------------------------------------------------")
import sqlite3
connection=sqlite3.connect("100-Days-Python/Day-37/students.db")
cursor=connection.cursor()
cursor.execute("""CREATE TABLE IF NOT EXISTS students(student_id,name)""")
cursor.execute("INSERT INTO students VALUES(?,?)",(1,"Bhoomi"))
cursor.execute("INSERT INTO students VALUES(?,?)",(2,"Anu"))
cursor.execute("INSERT INTO students VALUES(?,?)",(3,"Chethan"))
cursor.execute("INSERT INTO students VALUES(?,?)",(4,"Diya"))
conn=sqlite3.connect("100-Days-Python/Day-37/marks.db")
cursor=conn.cursor()
cursor.execute("""CREATE TABLE IF NOT EXISTS students(mark_id,student_idc,subject,marks)""")
cursor.execute("INSERT INTO students VALUES(?,?,?,?)",(1,8,"Bhoomi",85))
cursor.execute("INSERT INTO students VALUES(?,?,?,?)",(2,1,"Anu",95))
cursor.execute("INSERT INTO students VALUES(?,?,?,?)",(3,10,"Chethan",75))
cursor.execute("INSERT INTO students VALUES(?,?,?,?)",(4,17,"Diya",65))
connection.commit()
connection.close()