#Challenge-01
print("=============================================================================")
print("------------------------- Create a Database ---------------------------------")
print("=============================================================================")
import sqlite3
connection=sqlite3.connect("100-Days-Python/Day-34/students.db")
cursor=connection.cursor()
cursor.execute("CREATE TABLE IF NOT EXISTS students(name,marks)")
cursor.execute("INSERT INTO students VALUES(?,?)",("Bhoomi",85))
cursor.execute("INSERT INTO students VALUES(?,?)",("Sachin",95))
cursor.execute("INSERT INTO students VALUES(?,?)",("Krishna",75))
connection.commit()
cursor.execute("SELECT * FROM students")
students=cursor.fetchall()
print("Created Database:",students)
print("-----------------------------------------------------------------------------")

#Challenge-02
print("=============================================================================")
print("---------------------------- Student Search ---------------------------------")
print("=============================================================================")
connection=sqlite3.connect("100-Days-Python/Day-34/students.db")
cursor=connection.cursor()
search_name=input("Enter the name of the student to Search")
cursor.execute("SELECT * FROM students WHERE name=?",(search_name,))
students=cursor.fetchall()
print("Student Details:",students)
print("-----------------------------------------------------------------------------")

#Challenge-03
print("=============================================================================")
print("------------------------------ Update Marks ---------------------------------")
print("=============================================================================")
connection=sqlite3.connect("100-Days-Python/Day-34/students.db")
cursor=connection.cursor()
name=input("Enter student name:")
new_marks=int(input("Enter new marks:"))
cursor.execute("UPDATE students SET marks=? WHERE name=?",(new_marks,name))
connection.commit()
cursor.execute("SELECT * FROM students")
students=cursor.fetchall()
print("New Updated Database:",students)
#connection.close()
print("-----------------------------------------------------------------------------")

#Challenge-04
print("=============================================================================")
print("------------------------------ Delete Student -------------------------------")
print("=============================================================================")
name_to_dlt=input("Enter a name to delete:")
cursor.execute("DELETE FROM students WHERE name=?",(name_to_dlt,))
connection.commit()
cursor.execute("SELECT * FROM students")
students=cursor.fetchall()
print("Remaining Students",students)
#connection.close()
print("-----------------------------------------------------------------------------")

#Bonus-Challenge
print("=============================================================================")
print("------------------------------ Robot Sensor Database ------------------------")
print("=============================================================================")
import sqlite3
connection=sqlite3.connect("100-Days-Python/Day-34/sensors.db")
cursor=connection.cursor()
cursor.execute("""CREATE TABLE IF NOT EXISTS sensors(sensor_name,distance,status)""")
cursor.execute("INSERT INTO sensors VALUES(?,?,?)",("Ultrasonic",15,"Safe"))
cursor.execute("INSERT INTO sensors VALUES(?,?,?)",("Ultrasonic",25,"Obstacle"))
cursor.execute("INSERT INTO sensors VALUES(?,?,?)",("Ultrasonic",10,"Safe"))
cursor.execute("INSERT INTO sensors VALUES(?,?,?)",("Ultrasonic",40,"Obstacle"))
connection.commit()
cursor.execute("SELECT * FROM sensors WHERE distance<?",(20,))
safe_readings=cursor.fetchall()
for reading in safe_readings:
    print(reading)
connection.close()
print("-----------------------------------------------------------------------------")
print("------------------------- End of Day-34 Challenges --------------------------")
print("-----------------------------------------------------------------------------")